### ISSUE TITLE
[2017.7] Fix test_key_deploy ssh test

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1106]
This started failing yesterday suddenly on the 2017.7 branch.

- integration.ssh.test_key_deploy.SSHKeyDeployQuestionCase.test_key_deploy
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/ssh/test_key_deploy.py", line 49, in test_key_deploy
    assert self._run_ssh('localhost test.ping', timeout=5) == exp
AssertionError
```

https://jenkinsci.saltstack.com/job/2017.7/job/salt-ubuntu-1604-py2/lastCompletedBuild/testReport/

It is failing on many distros on the branch: https://jenkinsci.saltstack.com/job/2017.7/

**Comment by Ch3LL** [comment]
bisected it to this commit 8af2d580f3ded8adbbbc1c1db79ff20bc8a68395

from pr: https://github.com/saltstack/salt/pull/48636  

and for documentation purposes. This started occuring after this change: https://github.com/saltstack/kitchen-salt/blob/master/lib/kitchen/transport/runtests.rb

which does "it will shell out to the ssh binary, instead of using the ruby net-ssh gem, which is a ruby implementation of ssh, and doesn't handle anything being unstable in the network"
