### ISSUE TITLE
[fluorine] Many ssh tests failing on Debian 8 and 9 for Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1137]
This is happening on both the fluorine and develop branches on Debian 8 and 9, but basically the tests in the following files are failing:

- integration.ssh.test_jinja_filters
- integration.ssh.test_state

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-debian-9-py3/lastCompletedBuild/testReport/

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-debian-8-py3/lastCompletedBuild/testReport/

Python 2 tests are fine, something has gone awry with Python 3 tests.

@terminalmage Can you look into this?

**Comment by rallytime** [comment]
Looks like these same tests are failing on the Py3 Fedora 27 tests too: https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-fedora-27-py3/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
I wasn't able to reproduce this yesterday in testkitchen using the docker provisioner. Working on getting AWS creds and the ec2 provisioner set up in tk so that I can test using the images Jenkins is using.

One thing to note is that only salt-ssh tests are failing, and salt-ssh is timing out:

```
10:18:50,146 [tests.support.case                                        :316 ][ERROR   ] run_script timed out after 180 seconds (process killed)
10:18:50,147 [tests.support.case                                        :330 ][ERROR   ] run_script results for: salt-ssh  -W -ldebug -c /tmp/salt-tests-tmpdir/config -i --priv /tmp/salt-tests-tmpdir/config/key_test --roster-file /tmp/salt-tests-tmpdir/config/roster --out=json localhost state.sls jinja_filters.data_compare_dicts
return code: None
stdout:
None

stderr:
None
```

It's possible that a recent openssh change is causing some weirdness here.

**Comment by terminalmage** [comment]
After some troubleshooting, It appears that the thin tarball is being removed before it can be deployed, so it never gets deployed. I'm still digging on this and will resume doing so on Friday.

**Comment by terminalmage** [comment]
Actually, it seems like salt-ssh is looking in the wrong directory for the thin tarball, it looks like the cachedir is being changed at some point.

**Comment by terminalmage** [comment]
OK, I've noticed that the following is happening:

```
[DEBUG   ] WARNING: current code checksum c8017cd9501f67552a54577f5f31f8b972383e3730807b899d51dc863f390056 is different to d713938abfcb3facc44e84a60a77cc44917af60b13d0f06d5027b3c3e0284707.
```

This triggers a redeployment of the thin tarball because we reach [this block](https://github.com/saltstack/salt/blob/862c44c/salt/client/ssh/__init__.py#L1182-L1185):

```python
        if '_caller_cachedir' in self.opts:
            cachedir = self.opts['_caller_cachedir']
        else:
            cachedir = self.opts['cachedir']
```

The opts do not contain a `_caller_cachedir` key, so the cachedir is incorrectly set for the shimmed command, and therefore when salt-ssh goes to deploy the thin tarball, it tries to source it from the wrong location.

[This block](https://github.com/saltstack/salt/blob/862c44c/salt/client/ssh/__init__.py#L1058-L1063) determines whether or not we set `_caller_cachedir`:

```python
            if '_caller_cachedir' in self.opts:
                opts_pkg['_caller_cachedir'] = self.opts['_caller_cachedir']
            if 'known_hosts_file' in self.opts:
                opts_pkg['known_hosts_file'] = self.opts['known_hosts_file']
            else:
                opts_pkg['_caller_cachedir'] = self.opts['cachedir']
```

This is where I begin to get in a bit over my head when it comes to salt-ssh. I'm not sure what role the `known_hosts_file` plays, and why it would or would not be set.

**Comment by thatch45** [comment]
I think that the caller_cachedir is intended to allow the wrapper interface to have a reference to the cachedir on the machine calling salt-ssh so that the opts_pkg which has opts from the minions can have its own cachedir reference. so the cachedir should be used on the target system while the caller cachedir should be used on the calling system

**Comment by terminalmage** [comment]
After speaking some more with @thatch45 he noticed that it seemed like the `known_hosts_file` check in [https://github.com/saltstack/salt/blob/862c44c/salt/client/ssh/__init__.py#L1058-L1063](this block) referenced above was incorrectly located in the middle of the surrounding `if` and `else` blocks. Upon reading further I noticed that the `known_hosts_file` check was added in an earlier branch and appears to have moved to its current location in an incorrect merge conflict resolution.

More details and a fix are in https://github.com/saltstack/salt/pull/50120

**Comment by terminalmage** [comment]
With the fix noted in the PR referenced in the comment above, the tests are green (tests run in a PY3 Debian 9 instance on AWS).

```
================================================================================
OK (total=9317, skipped=1035, passed=8282, failures=0, errors=0)
============================  Overall Tests Report  ============================
```

**Comment by rallytime** [comment]
Fix confirmed.
