### ISSUE TITLE
[fluorine] arch test_cp failure

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1225]
integration.modules.test_cp.CPModuleTest.test_get_file_str_https

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-arch-py3/48/

**Comment by terminalmage** [comment]
I've opened https://github.com/saltstack/salt/pull/50788 to fix this. I was able to reproduce, but only the first time I ran the test. Subsequent runs worked. This appears to be some problem with DNS resolution, because I spawned another AWS box and the lookup for repo.saltstack.com failed using cURL initially, but then worked after that.

**Comment by terminalmage** [comment]
The latest branch build shows this test passed. Closing.
