### ISSUE TITLE
[fluorine] proxy test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1235]
integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_list_pkgs
integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_service_list

https://jenkinsci.saltstack.com/job/fluorine/view/Proxy/job/salt-centos-7-py2-proxy/39/

**Comment by twangboy** [comment]
Probably fixed by https://github.com/saltstack/salt/pull/50902

I can replicate this issue by setting the timeout to the run_call command to something really small... That generated the same error I'm seeing on jenkins. The above PR increases the timeout across the board for all commands used in the test suite. This will hopefully eliminate timeout issues for all tests.

This may be caused by the types of VM's we're spinning up on ec2. We may be expending our cpu credits early on in the test run, causing tests to run slower and time out.

**Comment by Ch3LL** [comment]
closing as these tests are passing now :)
