### ISSUE TITLE
[fluorine] fedora 28 auth test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1238]
the tests:

```
integration.shell.test_auth.AuthTest.test_pam_auth_valid_group
integration.shell.test_auth.AuthTest.test_pam_auth_valid_user
integration.shell.test_runner.RunTest.test_salt_run_with_eauth_all_args
```

are failing on fedora 28 python2 tests

https://jenkinsci.saltstack.com/job/fluorine/job/salt-fedora-28-py2/56/

**Comment by Ch3LL** [comment]
also this test as well: integration.shell.test_key.KeyTest.test_list_acc_eauth

**Comment by terminalmage** [comment]
Can't reproduce in docker, spinning up an AWS box now.

**Comment by terminalmage** [comment]
Was not able to reproduce in AWS either. Destroying box and recreating, will try again.

**Comment by terminalmage** [comment]
At least some of this appears to have been caused by SSSD issues on Fedora 28, which are non-fatal but nonetheless make the set_date/set_expire functions fail. https://github.com/saltstack/salt/pull/51079 fixes those issues in the shadow module. I made that fix in 2018.3 however, so it'll need to be merged forward into fluorine and then the tests will need to run after that merge, before we know how many of the failures were fixed by this.

**Comment by Ch3LL** [comment]
also fixes this possibly: https://github.com/saltstack/salt-jenkins/issues/1217

**Comment by terminalmage** [comment]
Apologies for the confusion, I meant to make the above comment on #1217. I actually still cannot reproduce these failures, even using an AWS box created using TestKitchen. The PAM eauth plugin is failing despite being configured correctly, and despite the `shadow.set_password` function returning `True` (suggesting that the password was properly set).

Here's some logging from the jenkins run. Note that I've redacted the password, though it doesn't matter since the user is removed (and the box is gone anyway).

```
10:28:36,737 [salt.auth             :297 ][WARNING ] Authentication failure of type "eauth" occurred.
10:28:36,737 [salt.master           :2085][WARNING ] Authentication failure of type "eauth" occurred.
10:28:36,740 [salt.transport.zeromq :226 ][DEBUG   ] Closing AsyncZeroMQReqChannel instance
10:28:36,741 [salt.transport.ipc    :394 ][DEBUG   ] Closing IPCMessageSubscriber instance
10:28:36,743 [salt.utils.lazy       :104 ][DEBUG   ] LazyLoaded nested.output
10:28:36,922 [tests.support.case    :503 ][DEBUG   ] Result of run_salt for command '-c /tmp/salt-tests-tmpdir/config -t 500 -a pam "*" test.ping --username saltdev --password REDACTED': ['Authentication error occurred.']
```

**Comment by Ch3LL** [comment]
did you try running the entire test suite?

**Comment by Ch3LL** [comment]
also just as a note these are failing on 2018.3 as well.

**Comment by Ch3LL** [comment]
also this test is failing and seems to be related: integration.shell.test_key.KeyTest.test_list_acc_eauth

**Comment by sagetherage** [comment]
Tom approved to remove this from 2019.2 - keeping it assigned to @terminalmage

**Comment by Ch3LL** [comment]
this is no longer failing on 2019.2.0.rc1, but still on 2018.3.4

**Comment by Ch3LL** [comment]
Issue moved to [saltstack/salt #51885](https://github.com/saltstack/salt/issues/51885) via [**ZenHub**](https://www.zenhub.com/)
