### ISSUE TITLE
[Python 3] Fix Arch Tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#430]
Currently the Python3 Arch tests are failing on the following tests:

unit.templates.test_jinja.TestGetTemplate.test_non_ascii
unit.templates.test_jinja.TestGetTemplate.test_non_ascii_encoding
integration.output.test_output.OutputReturnTest.test_output_unicodebad
unit.modules.test_zypper.ZypperTestCase.test_list_products
integration.modules.test_grains.TestModulesGrains.test_get_core_grains
integration.modules.test_archive.ArchiveTest.test_gunzip
integration.modules.test_archive.ArchiveTest.test_gzip
integration.modules.test_archive.ArchiveTest.test_tar_pack
integration.modules.test_archive.ArchiveTest.test_tar_unpack
integration.modules.test_archive.ArchiveTest.test_unzip
integration.modules.test_archive.ArchiveTest.test_zip
integration.states.test_user.UserTest.test_user_present_unicode
integration.modules.test_cp.CPModuleTest.test_get_file_str_https
integration.modules.test_cp.CPModuleTest.test_get_file_str_local
integration.modules.test_cp.CPModuleTest.test_get_url_file_no_dest
integration.modules.test_cp.CPModuleTest.test_get_file_gzipped
integration.modules.test_cp.CPModuleTest.test_get_url_file
integration.modules.test_cp.CPModuleTest.test_get_url_https
integration.modules.test_cp.CPModuleTest.test_get_url_https_dest_empty
integration.modules.test_state.StateModuleTest.test_requisites_prereq_simple_ordering_and_errors

The solution will be to ensure during the salt-jenkins git.salt phase we are correctly setting the locale to utf-8. This should resolve these test failures

**Comment by DmitryKuzmenko** [comment]
Results of the issue analysis.

What happens:

Minion is initially started with `LANG='C'`, then the test suite sets the locale using `locale.system` state that uses `locale.set_locale` module. This module sets the system locale but doesn't change the environment in which the minion is running. Also: since minion is a multiprocessing application it's not as easy as `os.environ['LANG'] = ...` to set locale runtime.

So if I'm right: the `locale` salt module sets the *system locale* as it described in the module docs. But all the currently running applications, including salt minion have to be restarted after it to apply the change.

So to fix the Arch Py3 locale related issues we have either to change salt-jenkins procedure to apply locale before run minion or to change the Arch image to have the `en_US.UTF-8` locale already set.

**Comment by DmitryKuzmenko** [comment]
@cachedout I can follow up after vacation or it have to be reassigned to somebody else.

**Comment by gtmanfred** [comment]
fixed by https://github.com/saltstack/salt-jenkins/pull/442
