### ISSUE TITLE
A couple of tests in integration.modules.test_groupadd failing on Fedora 25

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#559]
On Fedora 25 Develop the following tests are failing:

```
integration.modules.test_groupadd.GroupModuleTest.test_add_system_group
integration.modules.test_groupadd.GroupModuleTest.test_add_system_group_gid
```

https://jenkins.saltstack.com/job/branch_tests/job/develop/job/salt-linode-fedora25/396/

ping @terminalmage mind taking a look here?

**Comment by rallytime** [comment]
These should be fixed by https://github.com/saltstack/salt/pull/44543. The link above with the test failure is test run number 396, but the latest test run was number 399 (which is [here](https://jenkins.saltstack.com/job/branch_tests/job/develop/job/salt-linode-fedora25/399/)) and those two particular tests are not failing.

🎉 🎉 🎉 

I'm going to close this since these _should_ be fixed. We can re-open if they pop up again.
