### ISSUE TITLE
[oxygen] integration.ssh.test_state.SSHStateTest.test_state_sls_id is failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#593]
The following test is failing on the `oxygen` branch:

- integration.ssh.test_state.SSHStateTest.test_state_sls_id
```
Traceback (most recent call last):
  File "/testing/tests/integration/ssh/test_state.py", line 50, in test_state_sls_id
    self._check_dict_ret(ret=ret, val='__sls__', exp_ret=SSH_SLS)
  File "/testing/tests/integration/ssh/test_state.py", line 24, in _check_dict_ret
    for key, value in ret.items():
AttributeError: 'unicode' object has no attribute 'items'
```

**Comment by rallytime** [comment]
Update: @terminalmage has a fix for this, so I'll assign this to him and label appropriately.

**Comment by terminalmage** [comment]
This was caused by the recent deprecation of the `environment` parameter. The SSH wrappers for the state module still needed to be updated. Also, I found that a bunch of the functions in the salt-ssh state wrapper did not respect the SLS opts `saltenv` and `pillarenv`, as provided by `_get_opts()` in salt/modules/state.py.

Because I had recently pulled `_get_opts()` into `salt.utils.state` to make it accessible to `docker.sls_build`, and that PR remains unmerged, I've added my fix to that PR: https://github.com/saltstack/salt/pull/45038.
