### ISSUE TITLE
[oxygen] CentOS 7 failing 3 SSH CLI integration tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#808]
- integration.cli.test_custom_module.SSHCustomModuleTest.test_ssh_custom_module
- integration.cli.test_custom_module.SSHCustomModuleTest.test_ssh_regular_module
- integration.cli.test_custom_module.SSHCustomModuleTest.test_ssh_sls_with_custom_module

Possibly related to #805

https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent7-py2/lastCompletedBuild/#showFailuresLink

**Comment by gtmanfred** [comment]
This appears to have been solved by https://github.com/saltstack/salt/pull/45725 including on centos 6, even though #805 hasn't been solved by that.

The only one left is, https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent6-py2/lastFailedBuild/testReport/junit/integration.cli.test_custom_module/SSHCustomModuleTest/test_ssh_custom_module/ and that appears to be caused by ssh timing out because there is too much load on the box.
