### ISSUE TITLE
[develop] 4 minion pillar tests failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#828]
- integration.minion.test_pillar.DecryptGPGPillarTest.test_decrypt_pillar_alternate_delimiter
- integration.minion.test_pillar.DecryptGPGPillarTest.test_decrypt_pillar_deeper_nesting
- integration.minion.test_pillar.DecryptGPGPillarTest.test_decrypt_pillar_default_renderer
- integration.minion.test_pillar.DecryptGPGPillarTest.test_decrypt_pillar_explicit_renderer

https://jenkins.saltstack.com/job/develop/job/salt-dev-linode-ubuntu16/lastFailedBuild/#showFailuresLink

**Comment by DmitryKuzmenko** [comment]
The PR broken this test is https://github.com/saltstack/salt/pull/45781
The problem is that PR made GPG pillars to be decrypted from the beginning of the `-----BEGIN PGP MESSAGE-----` to the end of the `-----END PGP MESSAGE-----` marks. This means that now any heading and trailing characters are kept in the decoded data.
So if we have a newline in the encrypted message after the `END` mark that newline is kept.

In consideration of the new behavior allowing the text to be a compound of encrypted and unencrypted data we have to detect a single fully encrypted message in some way ignoring that newlines.

I'm thinking on a solution.
